// MIDI Captain config types - auto-generated from Rust structs via ts-rs
// DO NOT EDIT MANUALLY - types are generated from config-editor/src-tauri/src/config/
// To regenerate: cd config-editor/src-tauri && cargo test --lib
// Then copy bindings/*.ts to src/lib/bindings/

// Re-export all types from generated bindings
export type { ButtonColor } from './bindings/ButtonColor';
export type { ButtonMode } from './bindings/ButtonMode';
export type { OffMode } from './bindings/OffMode';
export type { MessageType } from './bindings/MessageType';
export type { Polarity } from './bindings/Polarity';
export type { DeviceType } from './bindings/DeviceType';
export type { BankSwitchMethod } from './bindings/BankSwitchMethod';
export type { ConditionOperator } from './bindings/ConditionOperator';
export type { ButtonState } from './bindings/ButtonState';
export type { Condition } from './bindings/Condition';
export type { MidiCommand } from './bindings/MidiCommand';
export type { ConditionalCommand } from './bindings/ConditionalCommand';
export type { CommandOrConditional } from './bindings/CommandOrConditional';
export type { StateOverride as GeneratedStateOverride } from './bindings/StateOverride';
export type { ButtonConfig as GeneratedButtonConfig } from './bindings/ButtonConfig';
export type { BankConfig as GeneratedBankConfig } from './bindings/BankConfig';
export type { MidiCaptainConfig as GeneratedMidiCaptainConfig } from './bindings/MidiCaptainConfig';
export type { EncoderPush } from './bindings/EncoderPush';
export type { EncoderConfig } from './bindings/EncoderConfig';
export type { ExpressionConfig } from './bindings/ExpressionConfig';
export type { ExpressionPedals } from './bindings/ExpressionPedals';
export type { DisplayConfig } from './bindings/DisplayConfig';
export type { SplashScreenConfig } from './bindings/SplashScreenConfig';
export type { BankSwitchConfig } from './bindings/BankSwitchConfig';

// Import types for augmentation
import type { ButtonConfig as GeneratedButtonConfig } from './bindings/ButtonConfig';
import type { StateOverride as GeneratedStateOverride } from './bindings/StateOverride';
import type { BankConfig as GeneratedBankConfig } from './bindings/BankConfig';
import type { MidiCaptainConfig as GeneratedMidiCaptainConfig } from './bindings/MidiCaptainConfig';
import type { CommandOrConditional } from './bindings/CommandOrConditional';
import type { ButtonMode } from './bindings/ButtonMode';
import type { MessageType } from './bindings/MessageType';
import type { OffMode } from './bindings/OffMode';

// Augment StateOverride with event array fields (skipped in ts-rs due to custom deserializer)
export interface StateOverride extends Omit<GeneratedStateOverride, 'press' | 'release' | 'long_press' | 'long_release'> {
  press?: CommandOrConditional[];
  release?: CommandOrConditional[];
  long_press?: CommandOrConditional[];
  long_release?: CommandOrConditional[];
}

// Augment ButtonConfig with event array fields (skipped in ts-rs due to custom deserializer)
// Also make type, mode, off_mode optional since Rust has defaults via #[serde(default)]
export interface ButtonConfig extends Omit<GeneratedButtonConfig, 'type' | 'mode' | 'off_mode' | 'states'> {
  type?: MessageType;
  mode?: ButtonMode;
  off_mode?: OffMode;
  press?: CommandOrConditional[];
  release?: CommandOrConditional[];
  long_press?: CommandOrConditional[];
  long_release?: CommandOrConditional[];
  double_press?: CommandOrConditional[];
  states?: StateOverride[];
}

// Augment BankConfig to use our custom ButtonConfig
export interface BankConfig extends Omit<GeneratedBankConfig, 'buttons'> {
  buttons: ButtonConfig[];
}

// Augment MidiCaptainConfig to use our custom ButtonConfig and BankConfig
export interface MidiCaptainConfig extends Omit<GeneratedMidiCaptainConfig, 'buttons' | 'banks'> {
  buttons?: ButtonConfig[];
  banks?: BankConfig[];
}

// Import ButtonColor for internal use in BUTTON_COLORS mapping
import type { ButtonColor } from './bindings/ButtonColor';

// Additional types not generated by Rust (UI-specific)
export type MidiTransport = 'usb' | 'trs' | 'both';

export interface DetectedDevice {
  name: string;
  path: string;
  config_path: string;
  has_config: boolean;
}

export interface ConfigError {
  message: string;
  details?: string[];
}

// Color mapping for UI - typed to ensure all ButtonColor variants are covered
export const BUTTON_COLORS: Record<ButtonColor, string> = {
  red: '#ff0000',
  green: '#00ff00',
  blue: '#0000ff',
  yellow: '#ffff00',
  cyan: '#00ffff',
  magenta: '#ff00ff',
  orange: '#ff8000',
  purple: '#8000ff',
  white: '#ffffff',
  pink: '#ff69b4',
  lime: '#00ff80',
  amber: '#ffbf00',
  teal: '#008080',
  violet: '#6600cc',
  gold: '#ffd700',
};
