// MIDI Captain config types - auto-generated from Rust structs via ts-rs
// DO NOT EDIT MANUALLY - types are generated from config-editor/src-tauri/src/config/
// To regenerate: cd config-editor/src-tauri && cargo test --lib
// Then copy bindings/*.ts to src/lib/bindings/

// Re-export all types from generated bindings
export type { ButtonColor } from './bindings/ButtonColor';
export type { ButtonMode } from './bindings/ButtonMode';
export type { OffMode } from './bindings/OffMode';
export type { MessageType } from './bindings/MessageType';
export type { Polarity } from './bindings/Polarity';
export type { DeviceType } from './bindings/DeviceType';
export type { BankSwitchMethod } from './bindings/BankSwitchMethod';
export type { ConditionOperator } from './bindings/ConditionOperator';
export type { ButtonState } from './bindings/ButtonState';
export type { Condition } from './bindings/Condition';
export type { MidiCommand } from './bindings/MidiCommand';
export type { ConditionalCommand } from './bindings/ConditionalCommand';
export type { CommandOrConditional } from './bindings/CommandOrConditional';
export type { StateOverride } from './bindings/StateOverride';
export type { ButtonConfig } from './bindings/ButtonConfig';
export type { EncoderPush } from './bindings/EncoderPush';
export type { EncoderConfig } from './bindings/EncoderConfig';
export type { ExpressionConfig } from './bindings/ExpressionConfig';
export type { ExpressionPedals } from './bindings/ExpressionPedals';
export type { DisplayConfig } from './bindings/DisplayConfig';
export type { SplashScreenConfig } from './bindings/SplashScreenConfig';
export type { BankConfig } from './bindings/BankConfig';
export type { BankSwitchConfig } from './bindings/BankSwitchConfig';
export type { MidiCaptainConfig } from './bindings/MidiCaptainConfig';

// Additional types not generated by Rust (UI-specific)
export type MidiTransport = 'usb' | 'trs' | 'both';

export interface DetectedDevice {
  name: string;
  path: string;
  config_path: string;
  has_config: boolean;
}

export interface ConfigError {
  message: string;
  details?: string[];
}

// Color mapping for UI
export const BUTTON_COLORS: Record<string, string> = {
  red: '#ff0000',
  green: '#00ff00',
  blue: '#0000ff',
  yellow: '#ffff00',
  cyan: '#00ffff',
  magenta: '#ff00ff',
  orange: '#ff8000',
  purple: '#8000ff',
  white: '#ffffff',
  pink: '#ff69b4',
  lime: '#00ff80',
  amber: '#ffbf00',
  teal: '#008080',
  violet: '#6600cc',
  gold: '#ffd700',
};
