// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankSwitchMethod } from "./BankSwitchMethod";

/**
 * Bank switching configuration
 */
export type BankSwitchConfig = { method: BankSwitchMethod, 
/**
 * [Legacy] Single button cycles through banks
 */
button: number | null, 
/**
 * Button for next bank (bank up) - takes precedence over 'button'
 */
button_next: number | null, 
/**
 * Button for previous bank (bank down)
 */
button_prev: number | null, cc: number | null, pc_base: number | null, channel: number | null, };
