// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonConfig } from "./ButtonConfig";

/**
 * Bank configuration for multi-bank mode
 */
export type BankConfig = { name: string, buttons: Array<ButtonConfig>, };
