// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Button trigger mode
 */
export type ButtonMode = "toggle" | "normal" | "momentary" | "select" | "tap";
