// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonColor } from "./ButtonColor";
import type { ButtonMode } from "./ButtonMode";
import type { MessageType } from "./MessageType";
import type { OffMode } from "./OffMode";
import type { StateOverride } from "./StateOverride";

/**
 * Button configuration
 */
export type ButtonConfig = { label: string, long_press_label?: string, long_press_color?: ButtonColor, 
/**
 * Whether to keep long_press_label visible indefinitely (default: true)
 * When false, label shows for 3s then returns to selected button
 */
long_press_label_persist?: boolean, 
/**
 * Whether to keep conditional labels (then_label/else_label) visible (default: false)
 * When false, label shows for 3s then returns to selected button
 */
conditional_label_persist?: boolean, color: ButtonColor, 
/**
 * Device profile ID (e.g., 'quad-cortex', 'helix')
 * When set with action_id, editor resolves to MIDI before saving
 */
profile_id?: string, 
/**
 * Action within profile (e.g., 'scene_b', 'snapshot_3')
 */
action_id?: string, double_press_timeout_ms?: number, type: MessageType, mode: ButtonMode, off_mode: OffMode, dim_brightness?: number, channel?: number, cc?: number, cc_on?: number, cc_off?: number, note?: number, velocity_on?: number, velocity_off?: number, program?: number, pc_step?: number, flash_ms?: number, value_on?: number, value_off?: number, default_on?: boolean, keytimes?: number, states?: Array<StateOverride>, select_group?: string, default_selected?: boolean, };
