// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionalCommand } from "./ConditionalCommand";
import type { MidiCommand } from "./MidiCommand";

/**
 * Union type for command arrays - can be regular MIDI commands or conditional wrappers
 */
export type CommandOrConditional = MidiCommand | ConditionalCommand;
