// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandOrConditional } from "./CommandOrConditional";
import type { Condition } from "./Condition";

/**
 * Conditional command wrapper for if/then/else logic
 */
export type ConditionalCommand = { type: "conditional", if: Condition, then: Array<CommandOrConditional>, else?: Array<CommandOrConditional>, then_label?: string, else_label?: string, };
