// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonState } from "./ButtonState";
import type { ConditionOperator } from "./ConditionOperator";

/**
 * Type of condition to evaluate
 */
export type Condition = { "type": "button_state", button: number, state: ButtonState, } | { "type": "button_keytime", button: number, keytime: number, } | { "type": "received_midi", cc: number, channel: number, operator: ConditionOperator, value: number, } | { "type": "expression", pedal: string, operator: ConditionOperator, value: number, } | { "type": "encoder", operator: ConditionOperator, value: number, };
