// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Device type
 */
export type DeviceType = "std10" | "mini6" | "nano4" | "duo2" | "one1";
