// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display text size settings
 */
export type DisplayConfig = { button_text_size?: string, status_text_size?: string, expression_text_size?: string, button_name_text_size?: string, };
