// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display text size settings
 */
export type DisplayConfig = { button_text_size: string | null, status_text_size: string | null, expression_text_size: string | null, button_name_text_size: string | null, };
