// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncoderPush } from "./EncoderPush";

/**
 * Rotary encoder configuration (STD10 only)
 */
export type EncoderConfig = { enabled: boolean, cc: number, label: string, min: number, max: number, initial: number, steps: number | null, push: EncoderPush | null, channel?: number, };
