// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonMode } from "./ButtonMode";

/**
 * Encoder push button configuration
 */
export type EncoderPush = { enabled: boolean, cc: number, label: string, mode: ButtonMode, channel?: number, cc_on?: number, cc_off?: number, };
