// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionConfig } from "./ExpressionConfig";

/**
 * Expression pedals container
 */
export type ExpressionPedals = { exp1: ExpressionConfig, exp2: ExpressionConfig, };
