// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Polarity } from "./Polarity";

/**
 * Expression pedal configuration
 */
export type ExpressionConfig = { enabled: boolean, cc: number, label: string, min: number, max: number, polarity: Polarity, threshold: number, channel: number | null, };
