// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message type for a button
 */
export type MessageType = "cc" | "note" | "pc" | "pc_inc" | "pc_dec";
