// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageType } from "./MessageType";

/**
 * MIDI command for multi-command event arrays
 */
export type MidiCommand = { type: MessageType, channel: number | null, cc: number | null, value: number | null, note: number | null, velocity: number | null, program: number | null, pc_step: number | null, threshold_ms: number | null, };
