// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageType } from "./MessageType";

/**
 * MIDI command for multi-command event arrays
 */
export type MidiCommand = { type: MessageType, channel?: number, cc?: number, value?: number, note?: number, velocity?: number, program?: number, pc_step?: number, data?: string, threshold_ms?: number, };
