// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankConfig } from "./BankConfig";
import type { BankSwitchConfig } from "./BankSwitchConfig";
import type { ButtonConfig } from "./ButtonConfig";
import type { DeviceType } from "./DeviceType";
import type { DisplayConfig } from "./DisplayConfig";
import type { EncoderConfig } from "./EncoderConfig";
import type { ExpressionPedals } from "./ExpressionPedals";
import type { SplashScreenConfig } from "./SplashScreenConfig";

/**
 * Complete MIDI Captain configuration
 */
export type MidiCaptainConfig = { device: DeviceType, global_channel: number | null, 
/**
 * Custom USB volume label (max 11 chars, alphanumeric + underscore).
 * Applied by boot.py via storage.remount() when the drive is enabled.
 */
usb_drive_name: string | null, 
/**
 * Development mode: when true the USB drive always mounts on boot without
 * needing to hold Switch 1.  Defaults to false (performance mode).
 */
dev_mode: boolean | null, 
/**
 * MIDI output transport: "usb" (default), "trs", or "both".
 * "usb"  — USB MIDI only (adafruit_midi over usb_midi.ports)
 * "trs"  — TRS/serial MIDI only (UART on GP16/GP17 at 31250 baud)
 * "both" — send to USB and TRS simultaneously
 */
midi_transport: string | null, 
/**
 * Array of banks (max 8 recommended for Flash storage)
 */
banks: Array<BankConfig> | null, 
/**
 * Bank switching configuration (method, button/CC/PC, channel)
 */
bank_switch: BankSwitchConfig | null, 
/**
 * Active bank on boot (0-indexed, default: 0)
 */
active_bank: number | null, 
/**
 * Legacy: single bank of buttons (auto-wrapped in banks[0] on load if banks not present)
 */
buttons: Array<ButtonConfig> | null, encoder: EncoderConfig | null, expression: ExpressionPedals | null, display: DisplayConfig | null, splash_screen: SplashScreenConfig | null, long_press_threshold_ms: number | null, double_press_timeout_ms: number | null, 
/**
 * Channel labels: optional mapping of channel numbers (as strings "0"-"15") to device names
 * Example: { "0": "Quad Cortex", "1": "Timespace Delay" }
 * Used in UI to show "Quad Cortex (Ch1)" instead of "Channel 1"
 * Uses BTreeMap instead of HashMap to ensure stable, sorted JSON output
 */
channel_labels: { [key in string]?: string } | null, };
