// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Splash screen configuration
 */
export type SplashScreenConfig = { enabled: boolean | null, duration_ms: number | null, idle_timeout_seconds: number | null, };
