// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonColor } from "./ButtonColor";

/**
 * Per-state overrides for keytimes cycling
 */
export type StateOverride = { cc?: number, cc_on?: number, cc_off?: number, note?: number, velocity_on?: number, velocity_off?: number, program?: number, pc_step?: number, color?: ButtonColor, label?: string, };
