// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonColor } from "./ButtonColor";
import type { CommandOrConditional } from "./CommandOrConditional";

/**
 * Per-state overrides for keytimes cycling
 */
export type StateOverride = { press: Array<CommandOrConditional> | null, release: Array<CommandOrConditional> | null, long_press: Array<CommandOrConditional> | null, long_release: Array<CommandOrConditional> | null, cc: number | null, cc_on: number | null, cc_off: number | null, note: number | null, velocity_on: number | null, velocity_off: number | null, program: number | null, pc_step: number | null, color: ButtonColor | null, label: string | null, };
